### PR TITLE
Fixed first article being jumbled on mobile

### PR DESCRIPTION
**Pull request by syndbg**
[Issue](http://i.imgur.com/QQRb8Q0l.png)

[Fixed](http://i.imgur.com/JnFxlZIl.png)

Reported by kind folks at https://www.reddit.com/r/learnprogramming/comments/30faqq/blog_post_learning_django_where_you_should_start/

### CODE REVIEW

**Comment by iKevinY** [comment]
Thanks for the pull request, @syndbg. I didn't really anticipate other people using this theme, so I didn't think to mention in the README that there is sort of a cap on the length of some of the header items, due to the nature of the absolute layout on mobile. For example, this is what my website looks like on mobile:



Since my site title is only one line long, everything fits with the current spacing. If I were to merge this PR in, it would add a large gap between the header and the content, since my header is a lot smaller than yours. Because of this, I am going to close this, so you might need to rely on using your fork which has spacing that works for your site.

**Comment by syndbg** [comment]
Thanks for the feedback @iKevinY !

I see that my approach is wrong altogether. I will research how to handle my issue without breaking the theme for other users :+1:

**Comment by iKevinY** [comment]
@syndbg I wouldn't say that your approach is wrong per se; since the theme uses absolute positioning for the header, it would require a rewrite of the positioning logic in order to make the header placement dynamic. In my opinion, the easiest course of action would be to just keep the fork you created and use that as the theme for your website.

**Comment by iKevinY** [comment]
@syndbg I've pushed 70a63195c66697ea8398fb7d60f8ffaf7417b4e7 which removes the use of absolute positioning to move the sidebar around (since it was suboptimal in the first place). The content and header should now dynamically adjust depending on how many lines the site description takes up.

**Pull request closed without merging**
